# Generated by Django 5.2.3 on 2025-07-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inf',
            name='descricao_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inf',
            name='descricao_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inf',
            name='descricao_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inf',
            name='descricao_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inf',
            name='titulo_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inf',
            name='titulo_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inf',
            name='titulo_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inf',
            name='titulo_pt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
