# Generated by Django 5.2.3 on 2025-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_inf_descricao_en_inf_descricao_es_inf_descricao_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('caminho', models.CharField(max_length=255)),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
